on:
  schedule:    
    - cron: '30 11 * * *'

jobs:
  scale_dyno_to_1:
    runs-on: ubuntu-latest
    name: scale dyno to 1
    steps:
      - name: scale dyno
        id: scale
        uses: deer42/heroku-scale-dyno@v1.0
        with:
          app_name: ${{ secrets.HEROKU_APP_NAME }}       
          email: ${{ secrets.EMAIL }}      
          api_key: ${{ secrets.HEROKU_API_KEY }}       
          process_type: worker
          new_scale: 0
